services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"